apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-app-ingress
spec:
  tls:
    - hosts:
        - "{{ .Values.app_name }}.dev.flexciton.net"
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.app_name }}.dev.flexciton.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-world-app-service
            port:
              number: 5000
