apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: hello-world-app
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres
              name: postgres-volume-mount
          envFrom:
            - secretRef:
                name: postgres-secret
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
