apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hello-world-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: azhzX3dvcmtzaG9w
